export const SelectedVideoData = [
  {
    video: "",
    describe:
      "AssignmentTable Tennis Rules AssignmentTable Tennis Rules AssignmentTable Tennis Rules AssignmentTable Tennis Rules AssignmentTable Tennis Rules AssignmentTable Tennis Rules Assignment",
    participate: 265,
    date: "23.05.21",
    play: 265,
    replay: 265,
    time: "130:56",
    chParticipate: [
      { date: new Date("2023-06-05"), value: 1 },
      { date: new Date("2023-07-09"), value: 2 },
      { date: new Date("2023-06-08"), value: 3 },
      { date: new Date("2023-07-10"), value: 2 },
    ],
    chPlay: [
      { date: new Date("2023-06-05"), value: 1 },
      { date: new Date("2023-06-09"), value: 2 },
      { date: new Date("2023-06-15"), value: 3 },
      { date: new Date("2023-07-10"), value: 1 },
    ],
    chReplay: [
      { date: new Date("2023-05-05"), value: 1 },
      { date: new Date("2023-06-09"), value: 1 },
      { date: new Date("2023-06-08"), value: 1 },
      { date: new Date("2023-07-10"), value: 2 },
    ],
    chTime: [
      { date: new Date("2023-06-15"), value: 50 },
      { date: new Date("2023-06-09"), value: 20 },
      { date: new Date("2023-06-28"), value: 30 },
      { date: new Date("2023-07-10"), value: 20 },
    ],
  },
];

export const zeroData = [];

const VideoData = [
  {
    video: "",
    describe:
      "Table Tennis Rules AssignmentTable Tennis Rules AssignmentTable Tennis Rules AssignmentTable Tennis Rules AssignmentTable Tennis Rules AssignmentTable Tennis Rules AssignmentTable Tennis Rules Assignment",
    participate: 956,
    date: "23.08.11",
    play: 55,
    replay: 15,
    time: "3:26",
    chParticipate: [
      { date: new Date("2023-06-05"), value: 1 },
      { date: new Date("2023-07-09"), value: 2 },
      { date: new Date("2023-06-08"), value: 3 },
      { date: new Date("2023-06-10"), value: 2 },
    ],
    chPlay: [
      { date: new Date("2023-06-05"), value: 1 },
      { date: new Date("2023-06-09"), value: 2 },
      { date: new Date("2023-06-15"), value: 3 },
      { date: new Date("2023-07-10"), value: 1 },
    ],
    chReplay: [
      { date: new Date("2023-05-05"), value: 1 },
      { date: new Date("2023-06-09"), value: 1 },
      { date: new Date("2023-06-08"), value: 1 },
      { date: new Date("2023-07-10"), value: 2 },
    ],
    chTime: [
      { date: new Date("2023-06-15"), value: 50 },
      { date: new Date("2023-06-09"), value: 20 },
      { date: new Date("2023-06-28"), value: 30 },
      { date: new Date("2023-07-10"), value: 20 },
    ],
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 856,
    date: "23.08.01",
    play: 890,
    replay: 390,
    time: "100:26",
    chParticipate: [
      { date: new Date("2023-06-05"), value: 1 },
      { date: new Date("2023-07-09"), value: 2 },
      { date: new Date("2023-06-08"), value: 3 },
      { date: new Date("2023-07-10"), value: 2 },
    ],
    chPlay: [
      { date: new Date("2023-06-05"), value: 1 },
      { date: new Date("2023-06-09"), value: 2 },
      { date: new Date("2023-06-15"), value: 3 },
      { date: new Date("2023-07-10"), value: 1 },
    ],
    chReplay: [
      { date: new Date("2023-05-05"), value: 1 },
      { date: new Date("2023-06-09"), value: 1 },
      { date: new Date("2023-06-08"), value: 1 },
      { date: new Date("2023-07-10"), value: 2 },
    ],
    chTime: [
      { date: new Date("2023-06-15"), value: 50 },
      { date: new Date("2023-06-09"), value: 20 },
      { date: new Date("2023-06-28"), value: 30 },
      { date: new Date("2023-07-10"), value: 20 },
    ],
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 1000,
    date: "23.05.10",
    play: 1000,
    replay: 1000,
    time: "100:26",
    chParticipate: [
      { date: new Date("2023-06-06"), value: 2 },
      { date: new Date("2023-07-02"), value: 1 },
      { date: new Date("2023-06-03"), value: 4 },
      { date: new Date("2023-07-14"), value: 4 },
    ],
    chPlay: [
      { date: new Date("2023-06-05"), value: 1 },
      { date: new Date("2023-06-06"), value: 2 },
      { date: new Date("2023-06-17"), value: 3 },
      { date: new Date("2023-07-18"), value: 1 },
    ],
    chReplay: [
      { date: new Date("2023-05-09"), value: 2 },
      { date: new Date("2023-06-02"), value: 2 },
      { date: new Date("2023-06-05"), value: 2 },
      { date: new Date("2023-07-19"), value: 3 },
    ],
    chTime: [
      { date: new Date("2023-06-15"), value: 30 },
      { date: new Date("2023-06-02"), value: 40 },
      { date: new Date("2023-06-20"), value: 20 },
      { date: new Date("2023-07-15"), value: 10 },
    ],
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "23.05.05",
    play: 900,
    replay: 2000,
    time: "30:26",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "url(<path-to-image>), lightgray 50% / cover no-repeat, #c4c4c4;",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
  {
    video: "",
    describe: "Table Tennis Rules Assignment",
    participate: 756,
    date: "21.10.11",
  },
];

export default VideoData;
